---

#    my $fields_text="
#    ip;
#    site;
#    vlan;
#10.40.0.2;den;1041;
#
#    net;172.31.10.24/30;
#
#    BGP_NEIGHBOR;172.31.10.25;
#    BGP_LOCAL;172.31.10.26
#
#    SRVNET1;SRVMED1;SRVIP1;10.69.1.0/24;1;10.69.1.1;
#    SRVNET2;SRVMED2;SRVIP2;10.69.2.0/24;3;10.69.2.1;
#    SRVNET3;SRVMED3;SRVIP3";10.69.3.0/24;2;10.69.3.1
# 64,512 – 65,534 – private AS numbers.

bgp:
    routerservers:
          - name:           "rr1"
            ip:             "10.40.0.101"
            site:           "den1"
            vlan:           "1041"
            net:            "172.31.10.100/30"
            BGP_LOCAL:      "172.31.10.101/30"
            BGP_NEIGHBOR:   "172.31.10.102/30"
            ASN_NEIGHBOR:   "65302"
            ASN:            "65301"
            vipnet:         "10.69.0.0/19"
          - name:           "rr2"
            ip:             "10.40.0.201"
            site:           "den1"
            vlan:           "1041"
            net:            "172.31.10.200/30"
            BGP_LOCAL:      "172.31.10.201/30"
            BGP_NEIGHBOR:   "172.31.10.202/30"
            ASN_NEIGHBOR:   "65302"
            ASN:            "65301"
            vipnet:         "10.69.0.0/19"
        
    router:
          - name:           "srx"
            hostip:         "10.40.0.1"
            site:           "den1"
            vlan:           "1041"
            net:            "172.31.10.100/30"
            BGP_LOCAL:      "172.31.10.102/30"
            BGP_NEIGHBOR:   "172.31.10.101/30"
            ASN_NEIGHBOR:   "65301"
            ASN:            "65302"                
          - name:           "srx"
            hostip:         "10.40.0.1"
            site:           "den1"
            vlan:           "1041"
            net:            "172.31.10.200/30"
            BGP_LOCAL:      "172.31.10.202/30"
            BGP_NEIGHBOR:   "172.31.10.201/30"
            ASN_NEIGHBOR:   "65301"
            ASN:            "65302"                
    servers:
          - name:           "nx1"
            ip:             "10.40.0.2"
            site:           "den1"
            ASNBASE:        "65000"
            ASN:        "65000"
            vips:          
                - vip: "10.69.1.1/24"
                  med: "1"
                - vip: "10.69.2.1/24"
                  med: "2"
                - vip: "10.69.3.1/24"
                  med: "3"            

          - name:           "nx2"
            ip:             "10.40.0.3"
            site:           "den1"
            ASNBASE:        "65000"
            ASN:        "65000"
            vips:          
                - vip: "10.69.1.1/24"
                  med: "3"
                - vip: "10.69.2.1/24"
                  med: "1"
                - vip: "10.69.3.1/24"
                  med: "2"            

          - name:           "nx3"
            ip:             "10.40.0.4"
            site:           "den1"
            ASNBASE:        "65000"
            ASN:        "65000"
            vips:          
                - vip: "10.69.1.1/24"
                  med: "2"
                - vip: "10.69.2.1/24"
                  med: "3"
                - vip: "10.69.3.1/24"
                  med: "1"            
